### ISSUE TITLE
meteorhacks:flow-router rename to kadira:flow-router

### ISSUE THREAD

**Issue by bySabi** [forwarder/autoform-wizard-flow-router#1]
`flow-router` change name to `kadira:flow-router`[https://github.com/kadirahq/flow-router],
same API.
Please update package

**Comment by bySabi** [comment]
Hello @Pagebakers review this PR too
Thanks.

**Comment by Pagebakers** [comment]
Awesome! thanks again!

**Comment by bySabi** [comment]
@Pagebakers don´t forget change README line: 

```
Wizard.useRouter('kadira:flow-router');
```
